FROM node:20-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY package.json pnpm-lock.yaml* .npmrc* ./

# Install dependencies
RUN CI=true pnpm install --shamefully-hoist

# Copy source code
COPY . .

EXPOSE 7340

CMD ["pnpm", "dev"]
