ALTER TABLE thoughts ADD COLUMN IF NOT EXISTS prev_id INTEGER REFERENCES thoughts(id) ON DELETE SET NULL;
ALTER TABLE thoughts ADD COLUMN IF NOT EXISTS next_id INTEGER REFERENCES thoughts(id) ON DELETE SET NULL;
